1. Создайте numpy array с элементами от числа N до 0 
(например, для N = 10 это будет array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])).

In [29]:
import numpy as np

In [30]:
x = np.arange( 0, 10 )
x[::-1]

array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

2. Создайте диагональную матрицу с элементами от N до 0. Посчитайте сумму ее значений на диагонали.

In [52]:
N = 10
x = np.diag(np.arange(N), k=0)
total = 0
Y = N
for i in range(0, N):
    x[i][i] = Y 
    total += x[i][i]
    Y -= 1
print(x)
print(total)

[[10  0  0  0  0  0  0  0  0  0]
 [ 0  9  0  0  0  0  0  0  0  0]
 [ 0  0  8  0  0  0  0  0  0  0]
 [ 0  0  0  7  0  0  0  0  0  0]
 [ 0  0  0  0  6  0  0  0  0  0]
 [ 0  0  0  0  0  5  0  0  0  0]
 [ 0  0  0  0  0  0  4  0  0  0]
 [ 0  0  0  0  0  0  0  3  0  0]
 [ 0  0  0  0  0  0  0  0  2  0]
 [ 0  0  0  0  0  0  0  0  0  1]]
55


3. Скачайте с сайта https://grouplens.org/datasets/movielens/ датасет любого размера. 
    Определите какому фильму было выставлено больше всего оценок 5.0.

In [56]:
import pandas as pd
ratings = pd.read_csv('ratings.csv', sep=',')
ratings.head()

userId  movieId  rating  timestamp
0       1        1     4.0  964982703
1       1        3     4.0  964981247
2       1        6     4.0  964982224
3       1       47     5.0  964983815
4       1       50     5.0  964982931

In [69]:
ratings[(ratings['rating'] == 5)].groupby('movieId').rating.count().reset_index(name = 'count').sort_values(['count'], ascending = False).head(1)

movieId  count
174      318    153

4. По данным файла power.csv посчитайте суммарное потребление стран Прибалтики (Латвия, Литва и Эстония) категорий 4, 12 и 21 за период с 2005 по 2010 года. 
Не учитывайте в расчетах отрицательные значения quantity.

In [76]:
x = pd.read_csv('power.csv', sep=',')
sum(x[((x['country'] == 'Latvia') | (x['country'] == 'Lithuania') | (x['country'] == 'Estonia')) & ((x['year'] >= 2005) & (x['year'] <= 2010)) & ((x['category'].isin)([4,12,21]) ) & (x['quantity'] >= 0)]['quantity'])

240580.0

5. Решите систему уравнений:
4x + 2y + z = 4 

x + 3y = 12

5y + 4z = -3


In [81]:
import numpy as np
x = np.array([[4, 2, 1], [1, 3, 0.], [0, 5, 4]])
z = np.array([4, 12, -3]) 
np.linalg.solve(x, z)

array([ 0.46666667,  3.84444444, -5.55555556])